version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: web
    ports:
      - "8888:80"
    depends_on:
      - "app"
  app:
    build:
      context: .
      dockerfile: ./go/Dockerfile
    container_name: app
    ports:
      - "3000:3000"
